### ISSUE TITLE
Are the gene-trait pairs all cross-tissue?

### ISSUE THREAD

**Issue by chilampoon** [hakyimlab/phenomexcan#1]
Hi, I am quite interested in the PhenomeXcan method. I was wondering what is the biological meaning of 'regional colocalization probability' (RCP)?  Is it something like aggregating the effects in each tissue made by a given gene?

Also, has fastENLOC got a tissue-specific method to give the RCP values in each tissue? or weights to show how much a gene-tissue pair contribute to the trait? Thanks!

**Comment by miltondp** [comment]
Hi @chilampoon, thank you for your interest.

RCP gives you the probability that the GWAS signal (for a trait) is colocalized with the eQTL signal (for a gene-tissue pair). Note that this works per tissue, and for the paper we have taken the maximum RCP across all tissues for a given gene-trait pair.

If you want to access the tissue-specific results, follow the instructions in the [main page](https://github.com/hakyimlab/phenomexcan) to access a Google Spreadsheet with the individual results for fastENLOC.

**Comment by chilampoon** [comment]
I see. I just didn't notice the Google Spreadsheet. Thank you!
